### PR TITLE
Bdbag minid

### PR DESCRIPTION
**Pull request by ismagilani**
These are my changes which allow file URL's in fetch.txt and rest api endpoint to work for all reference and non reference resource files.

### CODE REVIEW

**Comment by ismagilani** [comment]
@hyi, do we want to change the url of the ResourceFile to always be the download url? I made an isolated change to the ListItem function so that the rest api list of files shows a Django-irods download url for each file.  Previously it was showing a url like this: http://localhost:8000/resource/resource_id/data/contents/file_name.  Clicking on this URL didn’t cause a download to happen.  So I changed it to be consistent with how we are forming URLs of files in fetch.txt.

**Comment by hyi** [comment]
@ismagilani See this code snippet: https://github.com/heliumdatacommons/commonsshare/blob/master/hs_core/views/__init__.py#L473-L480
It maps resource file URL to django_irods download URL. I think you need to change this url mapper function to make the download to work, rather than only changing this single REST API function. This way, the URL mapper will apply across the board.

**Comment by ismagilani** [comment]
Are you sure that’s the code that’s invoked for resource files listed at http://localhost:8000/hsapi/resource/resource_id/files/?  The code I modified is the code that’s invoked for this REST api call.

If this is a sticking point for you, I can back out this change and we can merge the remaining changes that allow the download link to work correctly for reference files in fetch.txt.  That would make the demo complete for today.  I can defer pushing the rest api stuff until Monday.

**Comment by hyi** [comment]
@ismagilani Yes, I am pretty sure that is the url mapper that maps resource file url to download url. Have you tested REST API file download endpoint (i.e., not directly paste URL in web browser to download file, but through REST API call) and verified REST API file download endpoint does not work without your url mapping line for referenced files? If you have verified, then go ahead to merge this PR. Otherwise, I think it is better to take out this url mapping line for now until some test and verification are done.

**Comment by ismagilani** [comment]
Yes of course I have tested thoroughly.  I have to debug across the code to see which path is being invoked for REST api resource files list endpoint.  Like I said, I made an isolated change to not affect other places that might be using file.url().  I need to spend some time next week to see if we can change file.url() centrally to broadcast this change across other areas of CommonsShare.  But for now I think we are safe with my change.

**Comment by hyi** [comment]
@ismagilani OK. Then I am merging this, and will deploy it to beta to get ready for demo.

**Comment by ismagilani** [comment]
Thank you!!!!

**Pull request merged**
