### PR TITLE
minid generation and removal of DOI plus refactoring of bagit to bdbag work 

### PR DESCRIPTION
**Pull request by ismagilani**

### CODE REVIEW

**Comment by hyi** [comment]
@ismagilani After giving this a bit of more thought, I think we cannot deploy this minid feature alone to production without integrating bdbags work. The main reason behind my thinking is that after a minid is assigned to a resource, the resource bag cannot be modified and become permanent/published. However, without bdbags implementation, the bag that contains referenced files does not conform to bdbags spec, e.g., fetch.txt is not part of the bag, also bag-info.txt needs to be included as part of the bag as well. So BDBags feature has to be done to make a bag valid first before minid can be assigned to it. I suggest to keep this PR open and use the same PR to incorporate bdbags work as well. After bdbags work is incorporated in the PR, I'll review it, then we can go from there trying to get the PR deployed to production. Looping in @rayi113 and @clarisca to keep them posted as well.

**Comment by rayi113** [comment]
@hyi @ismagilani This is where the formerly optional but now required in bdbag file bag-info.txt will help.  In that file, we can differentiate 
- CommonsShare bags based on HydroShare
- CommonsShare bags based on BDBags
- CommonsShare bags based on the future CommonsBag spec

And begin publishing minids continuously.

mention @clarisca

**Comment by rayi113** [comment]
Example bdbag bag-info.txt contents:

Bag-Software-Agent: BDBag version: 1.2.4 (Bagit version: 1.6.4) <https://github.com/fair-research/bdbag>
BagIt-Profile-Identifier: https://raw.githubusercontent.com/fair-research/bdbag/master/profiles/bdbag-profile.json
Bagging-Date: 2018-04-23
Payload-Oxum: 632860.1

**Comment by ismagilani** [comment]
I agree Hong.  It was not my intention to wait for the bdbag work.

**Comment by hyi** [comment]
@rayi113 @ismagilani Note that we don't have bag-info.txt in HydroShare-based bag which is what we have now as part of this PR. Do we need to include at least bag-info.txt in the bag before releasing this minid feature? If so, with the current bagit implementation in iRODS, we'll have to augment the iRODS bagit rule to include this bag-info.txt. However, we are leaning toward getting bdbags implemented in Django to include fetch.txt for bags, so it will not be worth the effort to augment the iRODS bagit rule to include this bag-info.txt if we are doing away with iRODS bagit rule. So if we are OK with the current HydroShare bag without bag-info.txt, it is OK with me to release this minid feature to production without including bdbags work. Otherwise, it is probably better to release minid together with bdbags implementation.

**Comment by ismagilani** [comment]
We can generate the bag-info.txt file as a placeholder for now similar to fetch.txt.  We can populate it later as part of bdbag work.

**Comment by ismagilani** [comment]
Hong, sorry I misread your comment earlier and thought it to mean that we "can" deploy minid without bdbag.  Thus my comments prior.  

However, I am not sure I understand why we have to wait for the bdbag work.  Is it a requirement somewhere? I understand minid and bdbags are closely related but does that imply that one cannot exit without the other?

**Comment by hyi** [comment]
@ismagilani @rayi113 I don't think an empty placehoder files for bag-info.txt and fetch.txt would help unless we put valid contents into it. My main concern with releasing minid before we have a valid bag is that we cannot modify the bag after ''publishing" it with minid. However, if the current HydroShare bag without bag-info.txt and fetch.txt can be treated as a valid bag and is publishable, we can go ahead with releasing minid, otherwise, I think it'd be better to have at least some part of bdbag work done (e.g., create a valid bag-info.txt) before we release minid work to allow people to publish a bag.

**Comment by rayi113** [comment]
@hyi @ismagilani Having the possiblity of minids pointing to bags previously created with iRODS bagit rule (via HydroShare business logic) is not ideal without a bag-info.txt to state that.  I logged in to look at the irods proxy user in commonssharetestZone and there are only 8 bags there, and most with just a single test file in them, so one possibility is to consider implementing a stand-alone inplace bag translator from irule-derived bagit -> bdbags, though not an exhaustive translator covering all possibilities and edge cases, just something based on the simple single-item content of the bags that are there currently.  From the HydroShare irule-generated bagits, it would involve removing all .xml files, put the items in the contents directory in the data directory, remove  the contents directory, remove the readme.txt, refresh the bagit.txt, manifest-.,txt and tagminrest-.txt, and adding the fetch.txt when ready.  Once all bags in commonssharetestZone (and eventually commonsshareZone) are bdbags of some version, then minids should support publishing new versions of the bdbag, so may be a time to try that out also with old and new versions of just bdbags.  Whatever route we go, in my opinion we should not have former irule-derived bags in CommonsShare once the bdbag code is ready.

**Comment by ismagilani** [comment]
@rayi113 Are the bags in iRODS the ones produced from our testing? If so, can't they just be discarded?

**Comment by hyi** [comment]
@ismagilani @rayi113 I took a look at the resources created on commonsshare.org production site and there are just a few test resources there. This would not be an issue for us if we have updated bagit code to create a new bag. We only need to set bag-modified flag to be true to force bag to be regenerated when user downloads bag next time or when minid needs to be generated for the bag. So data migration for bagit would not pose a problem for us. However, once we deploy minid work to production, we cannot regenerate the bag since the bag is "published" hence my argument that to release minid work with some further work of bdbags to make our current bag publishable due to the publishing nature of minid.

**Comment by rayi113** [comment]
@hyi @ismagilani @rayi met and agreed to do bdbag first before deploying minid, so dependency on https://github.com/heliumdatacommons/MVP-repo/issues/68.

**Comment by hyi** [comment]
Closing since it is created against master. Use another PR created against develop instead.

**Pull request closed without merging**
